# Generated by Django 5.2.4 on 2025-08-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_topic_question_wronganswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(null=True),
        ),
    ]
